In [1]:
import numpy as np

In [2]:
lst = [1, 2, 4]
print(lst * 2)

[1, 2, 4, 1, 2, 4]


In [4]:
np_arr = np.array([1, 2, 3])
np_arr + 1
print(np_arr)

[1 2 3]


In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((3, 3))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

In [6]:
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [7]:
c = np.ones((3, 5))

In [8]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [15]:
a = np.array(((1, 2, 3,), (4, 5, 6)))
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
np.array(((1, 2, 3), (4, 5, 6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a = np.array(((1, 2, 3,), (4, 5, 6)))
a.shape

(2, 3)

In [20]:
np.ones((3, 3)).size

9

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[0]

array([1, 2, 3])

In [23]:
# Creates a NumPy array from a Python sequence such as list tuple.
a = np.array([1, 2, 3]) 
b = np.array((1, 2, 3))

# Creates 2D NumPy array from a Python sequence such as list tuple.
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array(((1, 2, 3,), (4, 5, 6)))

e = np.zeros((2, 3)) #Create an Array of Zeros
f = np.ones((3, 5)) #Create an Array of Ones
g = np.arange(0, 10, 2) #Create a Range of Values
h = np.linspace(0, 1, 5) #Create Evenly Spaced Values

print(a, b, c, d, e, f, g, h)


[1 2 3] [1 2 3] [[1 2 3]
 [4 5 6]] [[1 2 3]
 [4 5 6]] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


In [24]:
# Creates a NumPy array from a Python sequence such as list or tuple.
a = np.array([1, 2, 3]) 
b = np.array((1, 2, 3))

# Creates 2D NumPy array from a Python sequence such as list or tuple.
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array(((1, 2, 3), (4, 5, 6)))

e = np.zeros((2, 3))       # Create an Array of Zeros
f = np.ones((3, 5))        # Create an Array of Ones
g = np.arange(0, 10, 2)    # Create a Range of Values
h = np.linspace(0, 1, 5)   # Create Evenly Spaced Values

print(f'1D np.array with list: {a}')
print(f'1D np.array with tuple: {b}')
print(f'2D np.array with list: \n{c}')
print(f'2D np.array with tuple: \n{d}')
print(f'np.array with zeros: \n{e}')
print(f'np.array with ones: \n{f}')
print(f'np.array with range of numbers: {g}')
print(f'np.array with evenly spaced values: {h}')

1D np.array with list: [1 2 3]
1D np.array with tuple: [1 2 3]
2D np.array with list: 
[[1 2 3]
 [4 5 6]]
2D np.array with tuple: 
[[1 2 3]
 [4 5 6]]
np.array with zeros: 
[[0. 0. 0.]
 [0. 0. 0.]]
np.array with ones: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
np.array with range of numbers: [0 2 4 6 8]
np.array with evenly spaced values: [0.   0.25 0.5  0.75 1.  ]


In [25]:
import numpy as np

# Create a 2D NumPy array (2 rows, 3 columns) from a tuple of tuples
a = np.array(((1, 2, 3), (4, 5, 6)))

# Check the shape of the array: (rows, columns)
print(a.shape)  # Output: (2, 3) — means 2 rows and 3 columns

# Create a 3x3 array filled with ones
# .size gives the total number of elements in the array
print(np.ones((3, 3)).size)  # Output: 9 — 3 rows * 3 columns = 9 elements


(2, 3)
9


In [28]:
# Creates a NumPy array from a Python sequence such as list or tuple.
a = np.array([1, 2, 3]) 
b = np.array((1, 2, 3),  dtype=np.int16)

# Creates 2D NumPy array from a Python sequence such as list or tuple.
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array(((1, 2, 3), (4, 5, 6)))

e = np.zeros((2, 3))       # Create an Array of Zeros
f = np.ones((3, 5))        # Create an Array of Ones
g = np.arange(0, 10, 2)    # Create a Range of Values
h = np.linspace(0, 1, 5)   # Create Evenly Spaced Values

print(f'1D np.array with list: {a}')
print(f'1D np.array with tuple: {b}')
# print(f'2D np.array with list: \n{c}')
# print(f'2D np.array with tuple: \n{d}')
# print(f'np.array with zeros: \n{e}')
# print(f'np.array with ones: \n{f}')
# print(f'np.array with range of numbers: {g}')
# print(f'np.array with evenly spaced values: {h}')


1D np.array with list: [1 2 3]
1D np.array with tuple: [1 2 3]


In [32]:
type(a.dtype)

numpy.dtype[int64]

In [33]:
type(b.dtype)

numpy.dtype[int16]

In [34]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# np_arr[row, col]
a[0] # Accesses the element at row 0
a[:, 1]
a[1, :2]

array([4, 5])

In [52]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# [row, column]

# Basic Indexing
print(f'Access row 0: {a[0]}')
print(f'Access row 1 to end:\n{a[1:]}')
print(f'Access element at (0,2): {a[0, 2]}')

# Slicing
print(f'Access all rows, column 1: {a[:, 1]}')
print(f'Access row 1, first 2 columns: {a[1, :2]}')
print(f'Access full array:\n{a[:, :]}')
print(f'Access top-left 1x2 block: {a[:1, :2]}')
print(f'Access last row: {a[-1]}')

# Boolean Indexing

print(f'Boolean mask (a > 3):\n{a > 3}')
print(f'Elements greater than 3: {a[a > 3]}')

Access row 0: [1 2 3]
Access row 1 to end:
[[4 5 6]
 [7 8 9]]
Access element at (0,2): 3
Access all rows, column 1: [2 5 8]
Access row 1, first 2 columns: [4 5]
Access full array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Access top-left 1x2 block: [[1 2]]
Access last row: [7 8 9]
Boolean mask (a > 3):
[[False False False]
 [ True  True  True]
 [ True  True  True]]
Elements greater than 3: [4 5 6 7 8 9]


In [49]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [50]:
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
a[a > 3]

array([4, 5, 6, 7, 8, 9])