In [1]:
import numpy as np

In [2]:
lst = [1, 2, 4]
print(lst * 2)

[1, 2, 4, 1, 2, 4]


In [4]:
np_arr = np.array([1, 2, 3])
np_arr + 1
print(np_arr)

[1 2 3]


In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((3, 3))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

In [6]:
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [7]:
c = np.ones((3, 5))

In [8]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [15]:
a = np.array(((1, 2, 3,), (4, 5, 6)))
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
np.array(((1, 2, 3), (4, 5, 6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a = np.array(((1, 2, 3,), (4, 5, 6)))
a.shape

(2, 3)

In [20]:
np.ones((3, 3)).size

9